### ISSUE TITLE
Help finishing software

### ISSUE THREAD

**Issue by gcormier** [gcormier/eWeatherStation#1]
Need some motivation to drive this home. Is anyone willing to finish off the code to look a bit better?

- [ ] Horizontal aspect ratio
- [ ] Pull weather forecast
- [ ] Make GUI look good

I'm willing to send off the hardware to get this done. I'd send a fully assembled PCB. You would need your own Waveshare e-ink display, Acurite sensor, and the tools and knowledge to program it. (It'd be great to have some sort of history/indication of your ability to do so) 

(Battery is also up to you, but it can also be run off USB)

**Comment by rruggiero** [comment]
Hi,

I am willing to help you with the design and prototyping of any 3d printed case you care thinking about.  Is it intended for indoor or out door use, or maybe both ?

As for the UI, what did you have in mind for that ?

Cheers,

Rick (Queensland, Australia)

**Comment by gcormier** [comment]
Awesome! I think the case could be very simple, it merely needs to provide access to the USB port for charging. It is for interior use.

GUI also simple is fine. If it's just showing the various temperatures, a simple breakdown. If it's showing weather forecast, looks like there are already many many weatherstations that do that, so it could be just reworking those to be a bit smaller. https://learn.adafruit.com/epaper-weather-station

Thinking more about it,  I already have many devices that show me weather forecasts... Ecobee, phones, google speakers.. I've always cared more about what it actually is outside my house and not at the airport :)

In which case, the UI could simply be nicely formatted indoor and outdoor temps. Perhaps, depending on the season, the forecasted extremes (low/high) for the day? I am quite open to suggestion.

**Comment by gcormier** [comment]
Oh wow, this one looks like it already has some space in the bottom for an internal sensor - and room to the right easily for an external one.

https://github.com/andrei7c4/weatherdisplay

EDIT: Ah, this does not use arduino framework.

**Comment by gcormier** [comment]
Hey Rick, were you still interested?

**Comment by rruggiero** [comment]
H Greg,

I think you were looking for someone to look at the interface and case, is the correct.  Well, I would like to offer any assistance you may need on this project.

Kindest regards,
 
Rick Ruggiero

e: rick.ruggiero@gmail.com <mailto:rick.ruggiero@gmail.com>

**Comment by gcormier** [comment]
Yup that sounds good! If you want to send me an email with your address I
can send you the board in a week or two to start playing. As mentioned
you'll need your own e-ink display and programming tools.
