### ISSUE TITLE
eInk Research

### ISSUE THREAD

**Issue by gcormier** [gcormier/eWeatherStation#1]
Power-on
![image](https://user-images.githubusercontent.com/8388983/48096904-7e26cd80-e1e6-11e8-82bc-9249f976ae15.png)

Refresh?
![image](https://user-images.githubusercontent.com/8388983/48096918-87179f00-e1e6-11e8-8a76-4485201e7611.png)

Further details
![image](https://user-images.githubusercontent.com/8388983/48096925-8bdc5300-e1e6-11e8-90df-22d401134ece.png)

**Comment by gcormier** [comment]
![image](https://user-images.githubusercontent.com/8388983/48097135-fd1c0600-e1e6-11e8-8411-28d60c5624e1.png)

I think it's doubtful at seeing what's behind the plastic without destructive force.

**Comment by ZinggJM** [comment]
Hi,
I got my https://www.aliexpress.com/item/Xiaomi-MiaoMiaoCe-INK-Dispay-Digital-Moisture-Meter-High-Precision-Thermometer-Temperature-Humidity-Probe-Monitor-Sensor/32849412575.html some days ago.
I opened a general topic for gadgets with e-papers on the Arduino Displays Forum: https://forum.arduino.cc/index.php?topic=580293.0
It seems clear that this is a segmented e-paper display, but with the few lines on the connector there needs to be some electronics on the panel itself. You can see a darker part on an edge if you hold it against a light. But tearing it apart would be a waste of this nice thing.
Where did you find the adapter you use on your picture? could you provide a link?
Or could you create a screen-shot of the logic analyzer with better resolution?
Thank you for the link, I like this gadget!

**Comment by gcormier** [comment]
I custom made the breakout adapter to be able to intercept the traffic.

https://oshpark.com/shared_projects/FrXZVN28

After seeing how short the pulses are, and given it's segmented, I think I'm going to back away from this for now. It will probably need a very fast MCU to drive it, and given it's only segmented, it offers limited use for the project I had in mind. Still an incredibly cheap device for an e-ink display given the size.

**Comment by gcormier** [comment]
Ditching the idea and going with custom PCB and 4.2" eInk display.
